enum ActionTypes {
  RECRUITER_OFFER_REQUEST = "RECRUITER_OFFER_REQUEST",
  RECRUITER_OFFER_SUCCESS = "RECRUITER_OFFER_SUCCESS",
  RECRUITER_OFFER_FAILURE = "RECRUITER_OFFER_FAILURE",

  RECRUITER_OFFERS_REQUEST = "RECRUITER_OFFERS_REQUEST",
  RECRUITER_OFFERS_SUCCESS = "RECRUITER_OFFERS_SUCCESS",
  RECRUITER_OFFERS_FAILURE = "RECRUITER_OFFERS_FAILURE",

  CANDIDATE_OFFERS_REQUEST = "CANDIDATE_OFFERS_REQUEST",
  CANDIDATE_OFFERS_SUCCESS = "CANDIDATE_OFFERS_SUCCESS",
  CANDIDATE_OFFERS_FAILURE = "CANDIDATE_OFFERS_FAILURE",

  ALL_OFFERS_REQUEST = "ALL_OFFERS_REQUEST",
  ALL_OFFERS_SUCCESS = "ALL_OFFERS_SUCCESS",
  ALL_OFFERS_FAILURE = "ALL_OFFERS_FAILURE",

  OFFER_REQUEST = "OFFER_REQUEST",
  OFFER_SUCCESS = "OFFER_SUCCESS",
  OFFER_FAILURE = "OFFER_FAILURE",
}

export default ActionTypes;
