enum ActionTypes {
  RECRUITER_OFFERS_REQUEST = "RECRUITER_OFFERS_REQUEST",
  RECRUITER_OFFERS_SUCCESS = "RECRUITER_OFFERS_SUCCESS",
  RECRUITER_OFFERS_FAILURE = "RECRUITER_OFFERS_FAILURE",
}

export default ActionTypes;
