enum ActionTypes {
  AUTH_REQUEST = "AUTH_REQUEST",
  AUTH_SUCCESS = "AUTH_SUCCESS",
  AUTH_FAILURE = "AUTH_FAILURE",

  LOGOUT_REQUEST = "LOGOUT_REQUEST",
  LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
  LOGOUT_FAILURE = "LOGOUT_FAILURE",

  SOCKET_PRIVATE_CONNECT = "SOCKET_PRIVATE_CONNECT",
  SOCKET_CHAT_SEND_CONNECT = "SOCKET_CHAT_SEND_CONNECT",
  SOCKET_CHAT_RECEIVE_CONNECT = "SOCKET_CHAT_RECEIVE_CONNECT",
}

export default ActionTypes;
