name: Check tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      CI: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: yarn install

      - name: Run tests
        uses: yarn test
