import { Offer } from "../../models";

export const mockData: Offer[] = [
  {
    id: "1",
    title: "Golang developer",
    companyName: "Google Inc",
    location: "Warsaw, PL",
    bottomPayrange: 10000,
    topPayrange: 13000,
    currency: "PLN",
    description: "Lorem ipsum",
    status: "open",
    experience: "2 years",
    isNew: true,
  },
  {
    id: "2",
    title: "Project manager",
    companyName: "Netflix",
    location: "New york, US",
    experience: "0 years",
    status: "open",
    description: "Lorem ipsum",
  },
  {
    id: "3",
    title: "Junior Frontend Developer",
    companyName: "Infinite",
    location: "Warsaw, PL",
    experience: "1 year",
    bottomPayrange: 9000,
    topPayrange: 11000,
    currency: "PLN",
    description: "Lorem ipsum",
    status: "open",
    isNew: true,
  },
  {
    id: "4",
    title: "Shop cashier",
    companyName: "Biedronka",
    location: "Gdansk, PL",
    bottomPayrange: 2500,
    topPayrange: 3000,
    currency: "PLN",
    experience: "0 years",
    status: "open",
    description: "Lorem ipsum",
    isNew: true,
  },
  {
    id: "5",
    title: "Mechanic",
    companyName: "Freelancer",
    location: "Kraków, PL",
    isNew: true,
    experience: "0 years",
    status: "open",
    description: "Lorem ipsum",
  },
  {
    id: "6",
    title: "Software engineer",
    location: "Lodon",
    companyName: "Meta",
    bottomPayrange: 10000,
    topPayrange: 13000,
    currency: "EUR",
    experience: "0 years",
    status: "open",
    description: "Lorem ipsum",
  },
];
