export const mockData = [
  {
    id: "1",
    title: "Golang developer",
    company: "Google Inc",
    location: "Warsaw, PL",
    bottomPayRange: 10000,
    upperPayRange: 13000,
    currency: "PLN",
    isNew: true,
  },
  {
    id: "2",
    title: "Project manager",
    company: "Netflix",
    location: "New york, US",
  },
  {
    id: "3",
    title: "Junior Frontend Developer",
    company: "Infinite",
    location: "Warsaw, PL",
    bottomPayRange: 9000,
    upperPayRange: 11000,
    currency: "PLN",
  },
  {
    id: "4",
    title: "Shop cashier",
    company: "Biedronka",
    location: "Gdansk, PL",
    bottomPayRange: 2500,
    upperPayRange: 3000,
    currency: "PLN",
    isNew: true,
  },
  {
    id: "5",
    title: "Mechanic",
    company: "Freelancer",
    location: "Kraków, PL",
    isNew: true,
  },
  {
    id: "6",
    title: "Software engineer",
    company: "Meta",
    bottomPayRange: 10000,
    upperPayRange: 13000,
    currency: "EUR",
  },
];
