enum ActionTypes {
  CANDIDATE_PROFILE_REQUEST = "CANDIDATE_PROFILE_REQUEST",
  CANDIDATE_PROFILE_SUCCESS = "CANDIDATE_PROFILE_SUCCESS",
  CANDIDATE_PROFILE_FAILURE = "CANDIDATE_PROFILE_FAILURE",

  OTHER_CANDIDATE_PROFILE_REQUEST = "OTHER_CANDIDATE_PROFILE_REQUEST",
  OTHER_CANDIDATE_PROFILE_SUCCESS = "OTHER_CANDIDATE_PROFILE_SUCCESS",
  OTHER_CANDIDATE_PROFILE_FAILURE = "OTHER_CANDIDATE_PROFILE_FAILURE",

  RECRUITER_PROFILE_REQUEST = "RECRUITER_PROFILE_REQUEST",
  RECRUITER_PROFILE_SUCCESS = "RECRUITER_PROFILE_SUCCESS",
  RECRUITER_PROFILE_FAILURE = "RECRUITER_PROFILE_FAILURE",
}

export default ActionTypes;
