enum ActionTypes {
  CONVERSATIONS_REQUEST = "CONVERSATIONS_REQUEST",
  CONVERSATIONS_SUCCESS = "CONVERSATIONS_SUCCESS",
  CONVERSATIONS_FAILURE = "CONVERSATIONS_FAILURE",

  CONVERSATION_REQUEST = "CONVERSATION_REQUEST",
  CONVERSATION_SUCCESS = "CONVERSATION_SUCCESS",
  CONVERSATION_FAILURE = "CONVERSATION_FAILURE",
}

export default ActionTypes;
