enum ActionTypes {
  UNREAD_COUNTER_REQUEST = "UNREAD_COUNTER_REQUEST",
  UNREAD_COUNTER_SUCCESS = "UNREAD_COUNTER_SUCCESS",
  UNREAD_COUNTER_FAILURE = "UNREAD_COUNTER_FAILURE",

  UNREAD_COUNTER_INCREASE = "UNREAD_COUNTER_INCREASE",
  UNREAD_COUNTER_DECREASE = "UNREAD_COUNTER_DECREASE",

  CONVERSATIONS_REQUEST = "CONVERSATIONS_REQUEST",
  CONVERSATIONS_SUCCESS = "CONVERSATIONS_SUCCESS",
  CONVERSATIONS_FAILURE = "CONVERSATIONS_FAILURE",

  MARK_AS_READ = "MARK_AS_READ",
  MARK_AS_UNREAD = "MARK_AS_UNREAD",
  NEW_MESSAGE = "NEW_MESSAGE",

  CONVERSATION_REQUEST = "CONVERSATION_REQUEST",
  CONVERSATION_SUCCESS = "CONVERSATION_SUCCESS",
  CONVERSATION_FAILURE = "CONVERSATION_FAILURE",

  MESSAGES_APPEND = "MESSAGES_APPEND"
}

export default ActionTypes;
