enum ActionTypes {
  CONVERSATIONS_REQUEST = "CONVERSATIONS_REQUEST",
  CONVERSATIONS_SUCCESS = "CONVERSATIONS_SUCCESS",
  CONVERSATIONS_FAILURE = "CONVERSATIONS_FAILURE",

  MARK_AS_READ = "MARK_AS_READ",
  MARK_AS_UNREAD = "MARK_AS_UNREAD",
  NEW_MESSAGE = "NEW_MESSAGE",

  CONVERSATION_REQUEST = "CONVERSATION_REQUEST",
  CONVERSATION_SUCCESS = "CONVERSATION_SUCCESS",
  CONVERSATION_FAILURE = "CONVERSATION_FAILURE",

  MESSAGES_APPEND = "MESSAGES_APPEND"
}

export default ActionTypes;
